version: "3"
services:
  hugo:
    image: jojomi/hugo:0.65.0
    container_name: cocodev-org
    hostname: cocodev-org
    environment:
      - HUGO_THEME=academic
      - HUGO_WATCH=true
      # - HUGO_BASEURL=
    command:
      - /run.sh  # from Dockerfile
      - --buildFuture
      - --disableFastRender
      - --verbose
      - --port=26263
      - --liveReloadPort=26263
    volumes:
      - .:/src
      # use the volume mount below to inspect the hugo output, IFF needed
      # - ./build:/output
    ports: [ "26263:26263", ]
